In [ ]:
!gunzip SRA716608_SRS3391629.mat.gz

In [ ]:
import pandas as pd
import numpy as np
file_name='SRA716608_SRS3391629'
df=pd.read_csv(file_name+'.mat',sep='\t')
dic=pd.read_csv(file_name+'.clusters.txt',names=['name','tag'],header=None,sep=' ')
print('df',df.shape)
print('dic',dic.shape)

In [ ]:
dict1={}
# adding to dictionary 
for i in range(len(dic.name)):
    dict1[dic.name[i]]=dic.tag[i]
labels={}
dfn=pd.read_excel('C:/Users/mukha/Downloads/liver_sc_name.xlsx',header=None,sep=' ')
dfn.drop([0,1],axis=0,inplace=True)
dfn.drop([2,3],axis=1,inplace=True)
dfn.rename(columns={0:'A',1:'B'},inplace=True)
labels = dict(zip(dfn.A,dfn.B))
label=list(labels.values())
data=[]
n_rows=df.shape[0]
n_cols=df.shape[1]
df.rename(columns=dict1,inplace=True)

df=df.groupby(by=df.columns, axis=1).sum()
filter_col=[x for x in df if isinstance(x,str)]
df.drop(filter_col,axis=1,inplace=True)

NameError: ignored

In [ ]:
df.head(20)

In [ ]:
df.to_csv('SRA691388_SRS3173555.csv')

In [ ]:
df=pd.read_csv('SRA878024_SRS4660845.csv')

In [ ]:
# df.head()
df['Unnamed: 0']=df['Unnamed: 0'].str.split(pat='_',expand=True)[1]
df=df.transpose()

In [ ]:
df.head()

                        0      ...               25427
Unnamed: 0  ENSG00000274303.1  ...  ENSG00000036549.12
0                           0  ...                  16
1                           0  ...                   5
2                           0  ...                   0
3                           0  ...                   2

[5 rows x 25428 columns]

In [ ]:
df.to_csv('lungs_count.txt',sep='\t',index=True,header=False)